# Generated by Django 5.1.1 on 2024-10-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
