# Generated by Django 5.1.1 on 2024-10-02 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_shop_products_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='no', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.shops'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
    ]
