# Generated by Django 5.1.1 on 2024-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_products_created_at_remove_products_shop_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='shop',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
