# Generated by Django 5.1.1 on 2024-10-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_products_shop_products_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.shops'),
        ),
    ]
