# Generated by Django 5.1.1 on 2024-10-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cartitem_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItemm',
        ),
    ]
