# Generated by Django 5.1.1 on 2024-10-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_productsitemm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsItemm',
        ),
    ]
