# Generated by Django 5.1.1 on 2024-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_productsitemm'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantaty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
