# Generated by Django 5.1.1 on 2024-10-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_products_quantaty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Productss',
        ),
    ]
